DROP DATABASE IF EXISTS cms;
CREATE DATABASE IF NOT EXISTS cms;

CREATE USER IF NOT EXISTS 'wohii'@'%' IDENTIFIED BY 'soc';

GRANT ALL PRIVILEGES ON cms.* TO 'wohii'@'%';
GRANT CREATE, ALTER, DROP, REFERENCES ON *.* TO 'wohii'@'%';

FLUSH PRIVILEGES;
SHOW GRANTS FOR 'wohii'@'%';